### ISSUE TITLE
Consider way of passing metadata between job definition and instances

### ISSUE THREAD

**Issue by ahdel-r** [rfdonnelly/jobrnr#55]
Sometimes, a plugin may capture or add some useful metadata for a job definition or job instance that may be of interest to to other plugins.

Adding a metadata hash data member of some  sort to the job definition or job instance handle may help facilitate this need (especially when refactoring coding to get scope to the metadata isn't available).

I might be naïve of the capabilities behind the idosecresies of Ruby, so this might already be possible by adding to the options instance passed to the plugins; however, it would be nice to encapsulate special purposed metadata to the actual job definition or job instance, and this allows for users developing new plugins to easily take advantage of work already done by another plugin.

@rfdonnelly , have any thoughts on this? This type of feature has come in handy for me before when scaling the tool out to other users' use cases.

**Comment by rfdonnelly** [comment]
The nice (bad?) thing about Ruby is that you can (monkey patch)[https://en.wikipedia.org/wiki/Monkey_patch] existing classes.  In other words, a plugin could modify the Jobrnr::Job::Instance class to add a metadata object.

I agree it would be nice to have an official way to do this.  However, I foresee many complications/tradeoffs that would need to be addressed.  For example, if plugin A generates metadata on some event and plugin B expects to use that metadata on the same event, how do you ensure that plugin B receives the event after plugin A? This could be solved in various ways but at the cost of complexity.

I don't currently have a need for this but I like the idea. Can revisit if a use case presents itself. Thank you for the suggestion.

**Comment by ahdel-r** [comment]
Cool - didn't know about the monkey patch feature.
And yes, all use cases I've seen this useful for do not exist within the same event. Typically some information was picked up at an earlier event (e.g. job definition modification for use in the job instance), then the information was used at later event stages or for post application reporting of metrics (e.g. some information regarding the job instance or job reported in stats or pointers for various improvements to the user experience). Things do become complex if the data needs to be shared within the same event between plugins, but that could be solved a number of ways as you mentioned.

Essentially, some sort of metadata passing interface between plugins for extensibility and scalability is nice if the use case presents itself. It is hard for me to present this from a requirements perspective thought right now without an explicit general use case rather than a proprietary one. If I come up with one, I'll let you now.
